#!/usr/bin/env python3
"""从 nix/lib.nix 里把 writeShellScriptBin 的脚本提取成可执行 shell, 去掉 nix 插值。
—— 目的: 不用装 nix、不用上 Deck, 也能在任意 Linux 沙盒里跑激活器做健壮性验证。
用法: python3 .selftest/extract-activate.py [machine]
"""
import re, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
machine = sys.argv[1] if len(sys.argv) > 1 else None
if machine is None:
    m = open(os.path.join(ROOT, "machine.nix"), encoding="utf-8").read()
    machine = re.search(r'machine\s*=\s*"([^"]+)"', m).group(1)

lib = open(os.path.join(ROOT, "nix", "lib.nix"), encoding="utf-8").read()

m = re.search(r'steamos-nix-activate\s*=\s*pkgs\.writeShellScriptBin\s*"steamos-nix-activate"\s*\'\'(.*?)\'\';',
              lib, re.S)
if not m:
    raise SystemExit("未能在 lib.nix 中定位 steamos-nix-activate")
body = m.group(1)

# nix '' 字符串里的 ''${...} 是转义后的 shell 变量 → 还原
body = body.replace("''${", "${")
# 剩下的 ${...} 都是 nix 插值, 按下面这张表换成沙盒可用值
repl = {
    "${runtimePath}": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "${cfg.stateDir}": "/home/deck/.steamos-nix",
    "${cfg.activatePath}": "/home/deck/.steamos-nix/bin/steamos-nix-activate",
    "${machine}": machine,
}
for k, v in repl.items():
    body = body.replace(k, v)

leftover = sorted(set(re.findall(r'\$\{[^}]+\}', body)))
if leftover:
    print("WARN: 仍有未替换的 nix 插值: %s" % ", ".join(leftover), file=sys.stderr)

out = os.path.join(ROOT, ".selftest", "activate-test.sh")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("#!/usr/bin/env bash\n# AUTO-GENERATED by .selftest/extract-activate.py — do not edit.\n"
            "# machine=%s\n" % machine + body)
os.chmod(out, 0o755)
print("生成 %s (machine=%s, %d 字节)" % (out, machine, len(body)))
