#!/usr/bin/env python3
"""从 nix/lib.nix 里把 workbuddy 转发器提取成可执行 shell。
—— 目的: 在没有 nix、没有 Deck 的 Linux 沙盒里验证"系统原生优先"这条策略真的生效:
     有 /usr/bin/workbuddy 就 exec 它; 没有才依次退到系统 electron、nix electron;
     而且全程关掉 chromium sandbox。
   提取而非复制, 保证测试跟着实现走。
用法: python3 .selftest/extract-workbuddy.py
"""
import re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lib = open(os.path.join(ROOT, "nix", "lib.nix"), encoding="utf-8").read()

m = re.search(
    r'workbuddy = pkgs\.writeShellScriptBin "workbuddy" \'\'(.*?)\'\';', lib, re.S)
if not m:
    raise SystemExit("未能在 lib.nix 中定位 workbuddy 转发器")
body = m.group(1)

body = body.replace("''${", "${")

# nix 插值 → 沙盒可替换的间接层(由 b-harness 通过环境变量注入)
repl = {
    "${runtimePath}": "$WB_RUNTIMEPATH",
    "${cfg.workbuddyDir}": "$WB_APPDIR",
    "${cfg.workbuddyElectron}/bin/electron": "$WB_NIX_ELECTRON",
    "${cfg.workbuddyFlags}": "$WB_FLAGS",
}
for k, v in repl.items():
    body = body.replace(k, v)

leftover = sorted(set(re.findall(r'\$\{[^}]+\}', body)))
ALLOW = {"${STEAMOS_NIX_WORKBUDDY:-auto}", "${STEAMOS_NIX_SYSROOT:-/usr}",
         "${WORKBUDDY_DIR:-$WB_APPDIR}", "${WORKBUDDY_ELECTRON:-}",
         "${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}", "${GTK_IM_MODULE:-}",
         "${QT_IM_MODULE:-}", "${XMODIFIERS:-}"}
unexpected = [x for x in leftover if x not in ALLOW]
if unexpected:
    print("WARN: 仍有未替换的 nix 插值: %s" % ", ".join(unexpected))

out = os.path.join(ROOT, ".selftest", "workbuddy-test.sh")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("#!/bin/sh\n"
            "# AUTO-GENERATED by .selftest/extract-workbuddy.py — do not edit.\n"
            "# 从 nix/lib.nix 的 workbuddy 转发器提取。\n"
            "# 需要调用方提供: WB_APPDIR / WB_NIX_ELECTRON / WB_FLAGS / WB_RUNTIMEPATH\n"
            "# 可选: STEAMOS_NIX_SYSROOT(默认 /usr) / STEAMOS_NIX_WORKBUDDY\n"
            + body)
os.chmod(out, 0o755)
print("生成 %s (%d 字节)" % (out, len(body)))
