#!/usr/bin/env python3
"""从 nix/lib.nix 里把 harmonyos-sans 的 installPhase 提取成可执行 shell。
—— 目的: 不用装 nix、不用上 Deck, 也能在 Linux 沙盒里跑这段安装逻辑,
   验证"带空格的目录名 / AppleDouble 干扰文件 / 上游结构变化"三类回归点。
   提取而非复制粘贴, 是为了测试跟着实现走 —— 改了 lib.nix 测试就跟着变。
用法: python3 .selftest/extract-font.py
"""
import re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
lib = open(os.path.join(ROOT, "nix", "lib.nix"), encoding="utf-8").read()

m = re.search(
    r'harmonyos-sans = stdenvNoCC\.mkDerivation \{.*?installPhase = \'\'(.*?)\'\';',
    lib, re.S)
if not m:
    raise SystemExit("未能在 lib.nix 中定位 harmonyos-sans 的 installPhase")
body = m.group(1)

# nix '' 字符串里的 ''${...} 是转义后的 shell 变量 → 还原
body = body.replace("''${", "${")
# runHook 只在 nix 构建环境里有意义, 沙盒里去掉
body = re.sub(r'^\s*runHook \w+\s*$', '', body, flags=re.M)

leftover = sorted(set(re.findall(r'\$\{[^}]+\}', body)))
# $src / $out 由沙盒通过环境变量注入, 属于预期残留
unexpected = [x for x in leftover if x not in ("${src}", "${out}")]
if unexpected:
    print("WARN: 仍有未替换的 nix 插值: %s" % ", ".join(unexpected))

out = os.path.join(ROOT, ".selftest", "font-install-test.sh")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("#!/bin/sh\n"
            "# AUTO-GENERATED by .selftest/extract-font.py — do not edit.\n"
            "# 从 nix/lib.nix 的 harmonyos-sans.installPhase 提取。\n"
            "# 需要调用方提供: src=<解包后的字体根目录>  out=<安装目标>\n"
            + body)
os.chmod(out, 0o755)
print("生成 %s (%d 字节)" % (out, len(body)))
