#!/bin/sh
# AUTO-GENERATED by .selftest/extract-font.py — do not edit.
# 从 nix/lib.nix 的 harmonyos-sans.installPhase 提取。
# 需要调用方提供: src=<解包后的字体根目录>  out=<安装目标>

      mkdir -p "$out/share/fonts/truetype/harmonyos-sans-sc"
      # NOTE: 这个 zip 是 macOS 打的, 里面有 __MACOSX/ 与一堆 ._xxx.ttf 的
      # AppleDouble 元数据文件 —— 它们**也**匹配 '*.ttf', 不排除就会被当字体装进去
      # (fontconfig 扫到 0 字节的假 ttf 会告警甚至让该 family 不可用)。
      # .selftest 的 B11 专门守这个回归点。
      find "$src/HarmonyOS Sans/HarmonyOS_Sans_SC" -maxdepth 1 -type f \
        -name '*.ttf' ! -name '._*' \
        -exec install -m 0644 -t "$out/share/fonts/truetype/harmonyos-sans-sc" {} +
      if [ -z "$(ls -A "$out/share/fonts/truetype/harmonyos-sans-sc" 2>/dev/null)" ]; then
        echo "harmonyos-sans: 没捞出任何 ttf —— 上游 zip 结构变了?" >&2
        exit 1
      fi
