#!/bin/sh
# AUTO-GENERATED by .selftest/extract-workbuddy.py — do not edit.
# 从 nix/lib.nix 的 workbuddy 转发器提取。
# 需要调用方提供: WB_APPDIR / WB_NIX_ELECTRON / WB_FLAGS / WB_RUNTIMEPATH
# 可选: STEAMOS_NIX_SYSROOT(默认 /usr) / STEAMOS_NIX_WORKBUDDY

    # 系统路径排在最前: 让 WorkBuddy 看到系统库 / dbus / portal / 输入法模块,
    # 而不是 nix 那一套。nix 的 runtimePath 放最后, 只作兜底。
    export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$WB_RUNTIMEPATH"

    MODE=${STEAMOS_NIX_WORKBUDDY:-auto}
    # 仅 chroot / 沙盒测试需要改这个; 真机上就是 /usr
    SYSROOT=${STEAMOS_NIX_SYSROOT:-/usr}

    # ① 系统原生 wrapper —— 最理想的一条路: WorkBuddy 完全不在 nix 里
    if [ "$MODE" != nix ] && [ -x "$SYSROOT/bin/workbuddy" ] && [ ! -L "$SYSROOT/bin/workbuddy" ]; then
      exec "$SYSROOT/bin/workbuddy" "$@"
    fi

    # 能走到这里 = /usr 里那个 wrapper 已被原子升级冲掉(正是本方案要解决的问题)。
    # /opt 是 offload→home, 升级幸存, 所以 app payload 还在。
    DIR=${WORKBUDDY_DIR:-$WB_APPDIR}
    APP=""
    for cand in "$DIR/resources/app.asar.unpacked" "$DIR/resources/app.asar" "$DIR"; do
      [ -e "$cand" ] && { APP="$cand"; break; }
    done
    if [ -z "$APP" ]; then
      echo "workbuddy(nix): $DIR 下没有 app payload —— 先用 AUR 装 workbuddy(yay -S workbuddy)。" >&2
      exit 1
    fi

    # ②/③ 挑 electron: 系统的优先(ABI 与本机 native 模块一致), nix 的只兜底
    ELECTRON_BIN=${WORKBUDDY_ELECTRON:-}
    if [ -z "$ELECTRON_BIN" ]; then
      for c in "$SYSROOT/bin/electron" "$SYSROOT/bin/electron-"*; do
        [ -x "$c" ] && { ELECTRON_BIN="$c"; break; }
      done
    fi
    if [ -z "$ELECTRON_BIN" ]; then
      ELECTRON_BIN="$WB_NIX_ELECTRON"
      echo "workbuddy(nix): 系统 electron 不可用, 退回 nix electron —— 输入法/portal/原生插件可能异常, 重装 AUR electron 可恢复。" >&2
    fi

    # Electron/Chromium 的 sandbox 一律关掉 —— 要的是完整系统访问
    # (IBus 输入法模块、xdg-desktop-portal、dbus 通知/托盘都依赖它)
    export ELECTRON_DISABLE_SANDBOX=1
    NO_SANDBOX="--no-sandbox --disable-setuid-sandbox"

    # native 模块(.node)常要链接系统库; 追加而非覆盖, 且放末尾不抢 nix 的
    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$SYSROOT/lib:$SYSROOT/lib64"

    # 输入法(全机型统一 IBus, SteamOS 自带):
    #   系统已设就尊重(比如 KDE 的 plasma-workspace/env 已经设了), 全空才补。
    #   而且 **Wayland 下只补 XMODIFIERS** —— KWin 自己拉起输入法
    #   (kwinrc [Wayland] InputMethod); 再强设 GTK/QT_IM_MODULE 会让 WorkBuddy
    #   改走 XWayland 的 IM 模块, 结果候选框不跟随、甚至打不出中文。
    #   与 scripts/setup-ibus-xiaohe.sh 写出的 env 片段是同一套判断, 别改歪。
    if [ -z "${GTK_IM_MODULE:-}" ] && [ -z "${QT_IM_MODULE:-}" ] && [ -z "${XMODIFIERS:-}" ]; then
      if [ "${XDG_SESSION_TYPE:-}" = wayland ]; then
        export XMODIFIERS=@im=ibus
      else
        export GTK_IM_MODULE=ibus QT_IM_MODULE=ibus XMODIFIERS=@im=ibus
      fi
    fi

    exec "$ELECTRON_BIN" $NO_SANDBOX "$APP" $WB_FLAGS "$@"
  